# Generated by Django 6.0.4 on 2026-09-30 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_medicalrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prakriti', models.CharField(blank=True, max_length=50)),
                ('vikriti', models.CharField(blank=True, max_length=50)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('pulse_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True)),
                ('clinical_observations', models.TextField(blank=True)),
                ('assessment_notes', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_assessments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assessed_at'],
            },
        ),
    ]
