# Generated by Django 6.1.1 on 2026-10-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttherapy',
            name='phase',
            field=models.CharField(choices=[('PURVAKARMA', 'Purvakarma (Preparatory)'), ('PRADHANAKARMA', 'Pradhanakarma (Elimination)'), ('PASCHATKARMA', 'Paschatkarma (Restorative)')], default='PRADHANAKARMA', max_length=30),
        ),
    ]
