# Generated by Django 6.0.4 on 2026-09-30 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_patientavailability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_response', models.TextField(blank=True)),
                ('therapist_observations', models.TextField(blank=True)),
                ('progress_notes', models.TextField(blank=True)),
                ('discomfort_level', models.PositiveIntegerField(blank=True, null=True)),
                ('completed_successfully', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_therapy_progress', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='scheduling.therapysession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
